module.exports.sentences = [
    "안녕하세요, 만나서 반갑습니다.",
    "오늘은 날씨가 매우 좋아 보입니다.",
    "학교에서는 새로운 친구들을 만났어요.",
    "저는 음악을 듣는 것을 좋아해요.",
    "가족과 함께 보내는 시간이 소중해요.",
    "요즘은 책 읽는 것에 빠져 있어요.",
    "커피 한 잔이 기분을 전환시켜줘요.",
    "산책하며 자연 속에서 휴식을 취하고 싶어졌어요.",
    "일상 속에서 작은 기쁨을 찾아보세요.",
    "미소 짓는 것이 건강에 좋다고 해요.",
    "꿈을 이루기 위해 노력하는 모습이 멋져 보여요.",
    "좋은 음식과 함께하는 소중한 순간이에요.",
    "새로운 도전을 통해 자기계발을 꾸준히 하고 있어요.",
    "마음이 편안해지는 음악을 찾아보세요.",
    "여행은 새로운 경험이 가득하죠.",
    "자연의 아름다움에 감탄해 보세요.",
    "지속적인 학습은 끊임없는 성장을 가져옵니다.",
    "건강을 위해 규칙적인 운동이 필요해요.",
    "친구들과 함께하는 시간은 행복을 주는 법이에요.",
    "새로운 문화를 경험하는 것은 눈과 마음을 활기차게 만들어 줘요.",
    "힘든 일도 긍정적으로 바라보는 습관이 필요해요.",
    "자신을 이해하고 받아들이는 것이 중요합니다.",
    "새로운 아이디어에 열린 마음을 가지세요.",
    "예술은 감성을 표현하는 아름다운 방법 중 하나에요.",
    "좋은 책은 마음을 풍부하게 만들어 줄 수 있어요.",
    "봄에는 꽃이 피어나는 모습이 아름답죠.",
    "공부하는 과정에서의 성취감은 특별하게 느껴져요.",
    "어려운 상황에서도 긍정적인 마음을 유지하세요.",
    "작은 변화부터 시작해보세요.",
    "자연 속에서의 산책은 마음을 치유해 줄 수 있어요.",
    "사소한 것에 감사하는 마음을 가지세요.",
    "친절한 말과 행동은 주변을 따뜻하게 만들어 줍니다.",
    "좋은 꿈을 꾸고 일어나면 기분이 좋아질 거예요.",
    "노래를 부를 때 마음이 가벼워져요.",
    "휴식이 필요할 때는 적절한 휴가를 취하세요.",
    "선물은 작은 마음의 표현이에요.",
    "새로운 도전은 성장의 기회가 될 수 있어요.",
    "진실된 친구는 어려운 시간에 더 가까이에 있어 줄 거예요.",
    "하루에 한 번은 웃음짓기를 실천해보세요.",
    "노래를 듣고 춤추면 스트레스가 날아갈 것 같아요.",
    "가슴 따뜻해지는 이야기를 듣고 싶어져요.",
    "인생은 여러 모험으로 가득 차 있어요.",
    "나만의 시간을 즐겨보세요.",
    "과거의 실수에 대해 후회하지 말고 배움으로 삼아보세요.",
    "목표를 세우고 그에 맞게 행동하세요.",
    "자신을 사랑하는 것이 먼저에요.",
    "미소를 머금고 주변을 돌아보세요.",
    "주위의 아름다움에 주목해 보세요.",
    "어떤 일이든 최선을 다하면 후회가 없을 거예요.",
    "마음의 평화를 찾는 것이 중요해요.",
    "새로운 만남은 인생을 더 풍요롭게 만들어 줄 거예요.",
    "자연의 소리에 귀를 기울여 보세요.",
    "감사의 마음을 표현하는 것이 좋아요.",
    "자기 자신에게 관대해지는 것이 중요합니다.",
    "새로운 도전을 통해 자기 자신을 발전시켜 보세요.",
    "어려운 시기도 지나갈 터이니 힘을 내세요.",
    "소소한 행복을 찾아보세요.",
    "좋은 음악은 마음을 치유하는 힘이 있어요.",
    "친구와 함께하는 순간이 최고에요.",
    "지금 이 순간을 즐겨보세요.",
    "다양한 경험은 인생을 더 풍요롭게 만들어 줄 거예요.",
    "자신의 가치를 알고 존중하세요.",
    "감정을 솔직하게 표현하는 것이 중요합니다.",
    "힘든 일이 있으면 도움을 청하세요.",
    "각양각색의 사람들을 만나보세요.",
    "공감하는 마음으로 대화를 나누면 소중한 순간이에요.",
    "하루에 하나씩 목표를 이루어 보세요.",
    "눈에 띄지 않는 작은 기쁨을 발견해 보세요.",
    "마음이 편안한 곳에서 차 한 잔 하면 좋아요.",
    "새로운 도서를 읽는 것은 지식을 넓히는 좋은 방법이에요.",
    "꾸준한 노력이 큰 성취로 이어질 수 있어요.",
    "미래를 위한 계획을 세우는 것이 중요합니다.",
    "자신의 감정을 이해하고 받아들이세요.",
    "봄에는 새로운 시작의 기운이 느껴져요.",
    "주변에 감사한 마음을 전해보세요.",
    "나만의 특별한 취미를 찾아보세요.",
    "자연의 아름다움은 신비로움을 안겨줘요.",
    "꿈을 이루기 위해 노력하는 모습은 멋져 보여요.",
    "목표를 향해 한 발씩 나아가세요.",
    "자신을 믿고 도전해 보세요.",
    "새로운 환경에서의 도전은 성장을 가져올 수 있어요.",
    "고난과 역경을 이겨낼 강인한 의지가 필요해요.",
    "자연의 소리는 마음을 편안하게 만들어 줘요.",
    "좋은 친구는 인생의 보물이에요.",
    "자신을 사랑하는 것이 행복의 출발점이에요.",
    "노래를 듣고 감정을 표현해 보세요.",
    "새로운 도전에 기대감을 갖고 나아가세요.",
    "감사한 마음으로 살아가면 더 행복할 거예요.",
    "즐거운 일은 마음을 활기차게 만들어 줘요.",
    "자신에게 자주 박수를 치면서 응원해 보세요.",
    "노력에는 보상이 따라올 거예요.",
    "목표를 성취하면 쾌감이 가득할 거에요.",
    "자연의 아름다움에 감사하며 살아가세요.",
    "미소를 머금고 주위를 돌아다니면 기분이 좋아질 거예요.",
    "자신의 가치를 잘 알고 자랑스러워해 보세요.",
    "꿈을 향해 열정적으로 나아가세요.",
    "새로운 도전을 통해 성장하는 기쁨을 느껴보세요.",
    "주위의 아름다운 것들에 감사를 표현해 보세요.",
    "마음을 열고 새로운 사람들을 만나보세요.",
    "삶의 작은 순간들을 놓치지 마세요."
]


module.exports.nickname = [
    'NewYork','London','Tokyo','Paris','Beijing','Moscow','Berlin','Istanbul','Sydney','Cairo','Mumbai',
    'Seoul','Johannesburg','MexicoCity','Toronto','BuenosAires','Rome','Bangkok','Dubai','Jakarta','Lagos','Karachi','HongKong',
    'Singapore','Amsterdam','LosAngeles','Delhi','Chicago','Madrid','KualaLumpur','Vancouver','Riyadh','Shanghai','Lima','Minsk',
    'Manila','Munich','Stockholm','Vienna','Copenhagen','Oslo','Budapest','Athens','Lisbon','Astana','Hanoi','Havana','Ulaanbaatar',
    'Colombo','KuwaitCity','Tiger','Elephant','Giraffe','Lion','Panda','Koala','Dolphin','Cheetah','Kangaroo','Penguin','Zebra','Gorilla',
    'Jaguar','Owl','Octopus','Fox','Hummingbird','Crocodile','Parrot','Armadillo','Chimpanzee','Hedgehog','Sloth','Dalmatian',
    'Flamingo','PolarBear','RedPanda','Lemur','Rhinoceros','Quokka','Peacock','Hippopotamus','Platypus','Ostrich','Albatross','Stingray',
    'Chameleon','Starfish','Walrus','Pufferfish','Beaver','Toucan','Butterflyfish','GilaMonster','Ocelot','Iguana','Angelfish','Lemming',
    'RedFox','Puma','Manatee','Kingfisher','Salamander','Python','BlueJay','Quail','SandDollar','Antelope','Mantis','Axolotl',
    'Peafowl','Mongoose','Falcon','Raccoon','HumpbackWhale','Tapir','Firefly','TasmanianDevil','Pangolin','Lynx','Echidna','Cobra',
    'Orangutan','Seahorse','KomodoDragon','Tortoise','Bison','Dingo','Tarsier','Capybara','SeaTurtle','Pigeon','Quetzal','Gopher',
    'Warthog','Badger','Dugong','Caracal','Gannet','Vulture','Mole','Weasel','Wolverine','ElephantSeal'
]